import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer'
import type { DocumentProps } from '@react-pdf/renderer'
import { prisma } from '../prisma'
import type { Invoice, Payment } from '../../generated/prisma/client'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 12, fontFamily: 'Helvetica' },
  header: { fontSize: 20, marginBottom: 20, fontWeight: 'bold' },
  subheader: { fontSize: 14, marginBottom: 24, color: '#555' },
  row: { flexDirection: 'row', marginBottom: 6 },
  label: { width: 140, color: '#666' },
  value: { flex: 1 },
  amount: { marginTop: 24, fontSize: 16, fontWeight: 'bold' },
  footer: { marginTop: 40, fontSize: 10, color: '#999' },
})

function formatMYR(amount: number): string {
  return `RM ${amount.toFixed(2)}`
}

function formatDate(d: Date): string {
  return d.toISOString().slice(0, 10)
}

type PdfDocProps = {
  businessName: string
  clientName: string
  amount: number
  dueDate: Date
  kind: 'INVOICE' | 'RECEIPT'
  ref: string
}

function PdfDoc({ businessName, clientName, amount, dueDate, kind, ref }: PdfDocProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>{businessName}</Text>
        <Text style={styles.subheader}>{kind}</Text>
        <View style={styles.row}><Text style={styles.label}>Reference</Text><Text style={styles.value}>{ref}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Client</Text><Text style={styles.value}>{clientName}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Due Date</Text><Text style={styles.value}>{formatDate(dueDate)}</Text></View>
        <Text style={styles.amount}>{formatMYR(amount)}</Text>
        <Text style={styles.footer}>Generated by Kutip</Text>
      </Page>
    </Document>
  )
}

async function renderPdf(doc: React.ReactElement<DocumentProps>): Promise<Buffer> {
  const buf = await renderToBuffer(doc)
  return Buffer.from(buf)
}

/**
 * Pure renderer exposed for unit testing without a database.
 */
export async function renderInvoiceDocument(props: PdfDocProps): Promise<Buffer> {
  return renderPdf(<PdfDoc {...props} />)
}

export async function generateInvoicePdf(invoiceId: string): Promise<Buffer> {
  const invoice = await prisma.invoice.findUniqueOrThrow({
    where: { id: invoiceId },
    include: { client: { include: { business: true } } },
  })
  return renderInvoiceLike(invoice, 'INVOICE')
}

export async function generateReceiptPdf(paymentId: string): Promise<Buffer> {
  const payment = await prisma.payment.findUniqueOrThrow({
    where: { id: paymentId },
    include: { invoice: { include: { client: { include: { business: true } } } } },
  })
  return renderInvoiceLike(payment.invoice, 'RECEIPT')
}

function renderInvoiceLike(
  invoice: Invoice & { client: { name: string; business: { name: string } } },
  kind: 'INVOICE' | 'RECEIPT'
): Promise<Buffer> {
  const doc = (
    <PdfDoc
      businessName={invoice.client.business.name}
      clientName={invoice.client.name}
      amount={invoice.amount.toNumber()}
      dueDate={invoice.dueDate}
      kind={kind}
      ref={invoice.id}
    />
  )
  return renderPdf(doc)
}